### ISSUE TITLE
Add Tulsa Blotter Tables

### ISSUE THREAD

**Issue by sgelbart** [AyOK-Code/oscn#117]
Please add the Tulsa Blotter tables and models to the OSCN database.

# Schema

## tulsa_blotter_inmates
roster_id
first
last
middle
booking_id
gender
race
address
height
weight
zip
hair
eyes

### tulsa_blotter_arrests
inmate_id
arrest_date
arrest_time
arrested_by
booking_date
booking_time
release_date
release_time

### tulsa_blotter_offenses
arrest_id
description
case_number
court_date
bond_type
bond_amount
disposition

# What I'm looking for:
- Create associations properly:
  - Inmates belong to roster/roster has many inmates
  - Arrests belongs to inmates/inmates has many arrests
  - Offenses belong to arrests/arrests have many offenses
- Do name-spacing properly (see Doc)
- Remember foreign keys on your migrations
- Create tests

**Comment by AspiringDev51** [comment]
https://github.com/AyOK-Code/oscn/pull/118
