### ISSUE TITLE
Add doc_facilities table

### ISSUE THREAD

**Issue by holdenmitchell** [AyOK-Code/oscn#82]
Create a new table `doc_facilities` which contains a list of all of the DOC facilities that appear in the table `doc_statuses`.

```
# Table: doc_facilities
name:string
is_prison:boolean # be sure to default to false and set null to false
```

You can see all of the facilities by doing the following query:

```ruby
# rails console
Doc::Status.distinct.pluck(:facility)
```

You can use the following table to mark if the facility is a prison

[Prison Facilities-Table 1.csv](https://github.com/AyOK-Code/oscn/files/9122010/Prison.Facilities-Table.1.csv)

To populate the data, use a "one off" rake task that executes the query and populates the table, then loops through the CSV. In addition to populating the table, we will also want to link it back to the `Doc::Status` and the `Doc::Profile` by adding new columns `doc_facility_id` to both tables. Include this as the last step in the one-off rake task

### Checklist

- [x] Table/Model added
- [x] Spec for model
- [x] New table data populated
- [x] Data linked back to `Doc::Status` table and `Doc::Profile` table
- [x] Ability to load data via one-off rake task

**Comment by AspiringDev51** [comment]
https://github.com/AyOK-Code/oscn/pull/88
