### ISSUE TITLE
Link sentencing county to the OSCN county

### ISSUE THREAD

**Issue by holdenmitchell** [AyOK-Code/oscn#83]
# Description

Currently the oscn `counties` table has no link to the `sentencing_county` found in the `doc_sentences` table. Create a new descriptor table to house this information:

```
# doc_sentencing_county
name:string
county_id:references # links back to the counties table
```

Not all sentencing counties will link back to the counties table. Only the ones that end with the text `county court`

```
SELECT DISTINCT sentencing_county from doc_sentences where sentencing_county ilike '%county court%' order by sentencing_county
```

After adding this table, you'll also need to link these in the `doc_sentences` table by adding a column `doc_sentencing_county_id` to the table

### Checklist

- [x] Table/Model added
- [x] Spec for model
- [x] New table data populated
- [x] Data linked back to `Doc::Sentences` table
- [x] Ability to load data via one-off rake task

**Comment by AspiringDev51** [comment]
https://github.com/AyOK-Code/oscn/pull/89

**Comment by sgelbart** [comment]
Tested this locally. Will deploy and test on sandbox once scraper is back up.
