### ISSUE TITLE
Flag cases that are filed in error

### ISSUE THREAD

**Issue by holdenmitchell** [AyOK-Code/oscn#85]
# Description

Some cases get filed in error or are just blank. This can throw off the counts for orgs that want to know how many felonys, misdemeanors, etc... have been filed.

Mark these in the database under as a boolean field `is_error` on the `court_cases` table. Adjust the case scraper tasks so that if it runs across these, the record is marked as an error.

If the case later gets data attached to it, toggle the record back to `is_error` false.

**Comment by holdenmitchell** [comment]
Case Examples:

[CM-2017-4169](https://www.oscn.net/dockets/GetCaseInformation.aspx?db=oklahoma&number=CM-2017-4169)
[CM-2018-2097](https://www.oscn.net/dockets/GetCaseInformation.aspx?db=oklahoma&number=CM-2018-2097)
[TR-2016-19355](https://www.oscn.net/dockets/GetCaseInformation.aspx?db=oklahoma&cmid=3440275) - but this one has another legit case under [same Case Number](https://www.oscn.net/dockets/GetCaseInformation.aspx?db=oklahoma&cmid=3440276)
[CPC-2018-2396](https://www.oscn.net/dockets/GetCaseInformation.aspx?db=oklahoma&number=CPC-2018-2396)

**Comment by sgelbart** [comment]
Complete
